import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {normalizedTitle,regionalProductUrl,xboxStore,psnStore,nintendoStore,nintendoCatalogue,catalogueChoice,enrichStoreLinks} from './store-links.js';
const json=v=>Response.json(v);
const game={id:'1792227428',title:'Indiana Jones',platform:'xbox'};
function env(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0003_store_links.sql',import.meta.url),'utf8'));return {DB:{prepare(sql){const s=db.prepare(sql);let args;return{bind(...v){args=v;return this;},async first(){return s.get(...args)||null;},async run(){return s.run(...args);}};}}};}
function psPage(id,statusCode=200){return new Response('<title>Game</title><script id="__NEXT_DATA__" type="application/json">'+JSON.stringify({props:{pageProps:{statusCode,productId:id,locale:'zh-hant-hk'}}})+'</script>');}
test('typography normalization keeps edition and sequel distinctions',()=>{assert.equal(normalizedTitle("Assassin’s Creed®"),normalizedTitle("ASSASSIN'S CREED"));assert.notEqual(normalizedTitle('Brotato'),normalizedTitle('Brotato Nintendo Switch 2 Edition'));assert.notEqual(normalizedTitle('Game 2'),normalizedTitle('Game'));});
test('regional product URL allowlist rejects searches, credentials and wrong regions',()=>{assert.ok(regionalProductUrl('nintendo','https://ec.nintendo.com/JP/ja/titles/70010000000026'));assert.equal(regionalProductUrl('nintendo','https://ec.nintendo.com/US/en/titles/70010000000026'),undefined);assert.equal(regionalProductUrl('xbox','https://www.xbox.com/zh-TW/search/results?q=game'),undefined);assert.equal(regionalProductUrl('psn','https://evil.example/product/id'),undefined);assert.equal(regionalProductUrl('psn','https://user@store.playstation.com/zh-hant-hk/product/UP1003-X'),undefined);});
test('Xbox resolves real title ID without auth and fills missing image',async()=>{let called;const result=await xboxStore(game,async(u,o)=>{called=[u,o];return json({Products:[{ProductId:'9N8FQ28Z6QX3',LocalizedProperties:[{Images:[{ImagePurpose:'BoxArt',Uri:'//store-images.s-microsoft.com/cover.jpg'}]}]}]});});assert.equal(new URL(called[0]).searchParams.get('value'),game.id);assert.equal(new URL(called[0]).searchParams.get('market'),'TW');assert.equal(called[1].headers.Authorization,undefined);assert.ok(result.url.endsWith('/9N8FQ28Z6QX3'));assert.equal(result.cover,'https://store-images.s-microsoft.com/cover.jpg');});
test('Xbox name fallback requires unique exact name, never picks Deluxe',async()=>{const fetcher=async u=>u.includes('/lookup')?json({Products:[]}):json({Results:[{Products:[{ProductId:'9N8FQ28Z6QX3',Type:'Game',Title:'Indiana Jones'},{ProductId:'9N8FQ28Z6QX4',Type:'Game',Title:'Indiana Jones Deluxe'}]}]});assert.ok((await xboxStore(game,fetcher)).url.endsWith('9N8FQ28Z6QX3'));assert.equal(await xboxStore({...game,title:'Indiana'},fetcher),null);});
test('Xbox ambiguous ID and name matches stay unlinked',async()=>{assert.equal(await xboxStore(game,async()=>json({Products:[{ProductId:'9N8FQ28Z6QX3'},{ProductId:'9N8FQ28Z6QX4'}]})),null);assert.equal(await xboxStore(game,async u=>u.includes('/lookup')?json({Products:[]}):json({Results:[{Products:[{ProductId:'9N8FQ28Z6QX3',Type:'Game',Title:game.title},{ProductId:'9N8FQ28Z6QX4',Type:'Game',Title:game.title}]}]})),null);});
test('PS verifies Hong Kong PDP and matching title identifier',async()=>{const g={id:'PPSA26786_00',title:'Game'},id='UP1003-PPSA26786_00-GAME';const f=async u=>u.includes('titlecontainer')?json({id,container_type:'product'}):psPage(id);assert.equal((await psnStore(g,f)).url,`https://store.playstation.com/zh-hant-hk/product/${id}`);assert.equal(await psnStore(g,async u=>u.includes('titlecontainer')?json({id,container_type:'product'}):psPage(id,404)),null);assert.equal(await psnStore(g,async()=>json({id:'UP1003-PPSA00000_00-GAME',container_type:'product'})),null);});
test('PS empty ID catalogue falls back to exact name AND title ID',async()=>{const g={id:'PPSA28183_00',title:"Assassin's Creed Black Flag Resynced"},id='EP0001-PPSA28183_00-GAME';let query;const r=await psnStore(g,async u=>{if(u.includes('titlecontainer'))return new Response(null,{status:204});if(u.includes('tumbler')){query=u;return json({links:[{id,name:g.title},{id:'EP0001-PPSA00000_00-GAME',name:g.title}]});}return psPage(id);});assert.ok(query.includes('Assassins'));assert.equal(r.source,'psn-title-search-exact:HK');assert.ok(r.url.endsWith(id));});
test('Nintendo uses manual official redirect and rejects unrelated destinations',async()=>{const g={id:'0100d7b01ae58000',title:'Game'};let opts;assert.equal((await nintendoStore(g,async(u,o)=>{opts=o;return new Response(null,{status:307,headers:{Location:'/JP/ja/titles/70010000065385'}});})).url,'https://ec.nintendo.com/JP/ja/titles/70010000065385');assert.equal(opts.redirect,'manual');await assert.rejects(nintendoStore(g,async()=>new Response(null,{status:302,headers:{Location:'https://evil.example/JP/ja/titles/70010000065385'}})));});
test('Nintendo shared Switch 2 ID does not silently link the base edition',async()=>{const g={id:'01002ef01a316000',title:'Brotato - Nintendo Switch 2 Edition'};assert.equal(await nintendoStore(g,async()=>new Response(null,{status:307,headers:{Location:'/JP/ja/titles/70010000070379'}})),null);assert.ok(catalogueChoice(g,[{id:g.id,title:'Brotato',nsuid:'70010000070379'},{id:g.id,title:'Brotato Nintendo Switch 2 Edition',nsuid:'70010000113036'}]).url.endsWith('70010000113036'));});
test('Nintendo compact catalogue handles split UTF8 and duplicate editions',async()=>{const g={id:'01002ef01a316000',title:'Brotato Nintendo Switch 2 Edition'};const bytes=new TextEncoder().encode(JSON.stringify({version:1,byId:{[g.id]:[['70010000070379','Brotato'],['70010000113036',g.title]]},byTitle:{}},null,4));const stream=new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close();}});const rows=await nintendoCatalogue([g],async()=>new Response(stream));assert.equal(rows.get(g.id).length,2);assert.ok(catalogueChoice(g,rows.get(g.id)).url.endsWith('70010000113036'));});
test('successful D1 mapping lasts 30 days and fresh cache makes zero upstream calls',async()=>{const e=env(),time=1000000;const data={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(data,e,async()=>json({Products:[{ProductId:'9N8FQ28Z6QX3'}]}),time);const row=await e.DB.prepare('SELECT * FROM gaming_store_links').bind().first();assert.equal(row.expires_at-time,30*86400000);let calls=0;const next={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(next,e,async()=>{calls++;throw Error('failure');},time+1);assert.equal(calls,0);assert.equal(next.recent[0].url,data.recent[0].url);});
test('transient store failure keeps stale link and retries after an hour',async()=>{const e=env(),time=1000000,data={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(data,e,async()=>json({Products:[{ProductId:'9N8FQ28Z6QX3'}]}),time);const next={platform:'xbox',recent:[{...game}]},now=time+31*86400000;await enrichStoreLinks(next,e,async()=>{throw Error('secret upstream body');},now);assert.equal(next.recent[0].url,data.recent[0].url);const row=await e.DB.prepare('SELECT * FROM gaming_store_links').bind().first();assert.equal(row.expires_at-now,3600000);assert.ok(!JSON.stringify(row).includes('secret'));});
test('changed title invalidates cache without inheriting another edition',async()=>{const e=env(),data={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(data,e,async()=>json({Products:[{ProductId:'9N8FQ28Z6QX3'}]}),1000);const next={platform:'xbox',recent:[{...game,title:game.title+' Deluxe'}]};await enrichStoreLinks(next,e,async()=>{throw Error('down');},1001);assert.equal(next.recent[0].url,undefined);});
test('negative lookup is cached for one day; database failure never breaks profile',async()=>{const e=env(),data={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(data,e,async u=>u.includes('/lookup')?json({Products:[]}):json({Results:[]}),1000);assert.equal((await e.DB.prepare('SELECT * FROM gaming_store_links').bind().first()).expires_at,1000+86400000);assert.equal(await enrichStoreLinks(data,{DB:{prepare(){throw Error('database');}}}),data);});

test('manual override survives display-name changes and automatic refresh',async()=>{
 const e=env(),url='https://www.xbox.com/zh-TW/games/store/game/9N8FQ28Z6QX4';await e.DB.prepare('INSERT INTO gaming_store_links(platform,game_id,title,url,source,checked_at,expires_at) VALUES(?,?,?,?,?,?,?)').bind('xbox',game.id,'old title',url,'manual',0,9999999999999).run();let calls=0;const data={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(data,e,async()=>{calls++;});assert.equal(calls,0);assert.equal(data.recent[0].url,url);
});
test('manual correction during catalogue lookup wins over automatic result',async()=>{
 const e=env(),url='https://www.xbox.com/zh-TW/games/store/game/9N8FQ28Z6QX4',data={platform:'xbox',recent:[{...game}]};await enrichStoreLinks(data,e,async()=>{await e.DB.prepare('INSERT INTO gaming_store_links(platform,game_id,title,url,source,checked_at,expires_at) VALUES(?,?,?,?,?,?,?)').bind('xbox',game.id,game.title,url,'manual',0,9999999999999).run();return json({Products:[{ProductId:'9N8FQ28Z6QX3'}]});});assert.equal(data.recent[0].url,url);assert.equal((await e.DB.prepare('SELECT source FROM gaming_store_links').bind().first()).source,'manual');
});
