const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('public/sveltia/accounts.js','utf8');
async function setup(search='',hash=''){
 const elements=new Map();class Element{constructor(tag){this.tag=tag;this.children=[];this.hidden=false;this.open=false;this.value='';this.textContent='';this.listeners={};}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;}addEventListener(type,fn){this.listeners[type]=fn;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);};let historyCleared=false;
 const accounts=['nintendo','psn','xbox','steam','gog','epic'].map(platform=>({platform,name:platform,status:'disconnected',missing:[]}));
 const fetch=async url=>new Response(JSON.stringify(url.endsWith('/bind/psn')?{mode:'assisted',state:'fixture',input:'npsso',url:'https://www.playstation.com/'}:url.includes('/complete/')?{error:'PSN_AUTHORIZE_FAILED'}:{accounts,history:[]}),{status:url.includes('/complete/')?503:200});
 vm.runInNewContext(source,{document:{getElementById:get,createElement:t=>new Element(t)},window:{addEventListener(){}},fetch,URL,URLSearchParams,AbortSignal,location:{search,hash,pathname:'/sveltia/accounts.html',assign(){}},history:{replaceState(){historyCleared=true;}},setTimeout,clearTimeout,confirm:()=>true});await new Promise(r=>setImmediate(r));return {get,historyCleared};
}
test('binding failure remains visible inside modal and exposes restart rather than disappearing',async()=>{const {get}=await setup();const ps=get('accounts').children.find(c=>c.children[0].textContent==='psn');await ps.children.at(-1).children[0].onclick();assert.equal(get('connect-dialog').open,true);get('connect-input').value='fixture';await get('connect-form').onsubmit({preventDefault(){}});assert.equal(get('connect-dialog').open,true);assert.match(get('connect-message').textContent,/PS NPSSO/);assert.equal(get('restart-connect').hidden,false);assert.equal(get('confirm-connect').disabled,true);});
test('callback error is displayed and query removed from browser history',async()=>{const {get,historyCleared}=await setup('?error=XBOX_TOKEN_UPSTREAM_HTTP_400');assert.equal(historyCleared,true);assert.match(get('message').textContent,/Microsoft/);});
test('Nintendo helper result opens confirmation and clears URL fragment without storing tokens',async()=>{const url='npf5c38e31cd085304b://auth#state='+('a'.repeat(43))+'&session_token_code=fixture';const {get,historyCleared}=await setup('','#nintendo-result='+encodeURIComponent(url));assert.equal(historyCleared,true);assert.equal(get('connect-dialog').open,true);assert.equal(get('connect-input').value,url);assert.equal(get('official-login').hidden,true);assert.doesNotMatch(source,/localStorage|sessionStorage/);});
