const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync('public/sveltia/accounts.js','utf8');
async function setup(search='',hash=''){
 const elements=new Map();class Element{constructor(tag){this.tag=tag;this.children=[];this.hidden=false;this.open=false;this.value='';this.textContent='';this.listeners={};}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;}addEventListener(type,fn){this.listeners[type]=fn;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);};let historyCleared=false;
 const accounts=['nintendo','psn','xbox','steam','gog','epic'].map(platform=>({platform,name:platform,status:'disconnected',missing:[]}));
 const calls=[];const fetch=async(url,options)=>{calls.push({url,body:options.body});return new Response(JSON.stringify(url.endsWith('/bind/nintendo')?{mode:'assisted',state:'a'.repeat(43),input:'callback',url:'https://accounts.nintendo.com/'}:url.endsWith('/bind/psn')?{mode:'assisted',state:'fixture',input:'npsso',url:'https://www.playstation.com/'}:url.endsWith('/complete/nintendo')?{status:'connected'}:url.includes('/complete/')?{error:'PSN_AUTHORIZE_FAILED'}:{accounts,history:[]}),{status:url.includes('/complete/')&&!url.endsWith('/complete/nintendo')?503:200});};
 vm.runInNewContext(source,{document:{getElementById:get,createElement:t=>new Element(t)},window:{addEventListener(){}},fetch,URL,URLSearchParams,AbortSignal,location:{search,hash,pathname:'/sveltia/accounts.html',assign(){}},history:{replaceState(){historyCleared=true;}},setTimeout,clearTimeout,confirm:()=>true});await new Promise(r=>setImmediate(r));return {get,historyCleared,calls};
}
test('binding failure remains visible inside modal and exposes restart rather than disappearing',async()=>{const {get}=await setup();const ps=get('accounts').children.find(c=>c.children[0].textContent==='psn');await ps.children.at(-1).children[0].onclick();assert.equal(get('connect-dialog').open,true);get('connect-input').value='fixture';await get('connect-form').onsubmit({preventDefault(){}});assert.equal(get('connect-dialog').open,true);assert.match(get('connect-message').textContent,/PS NPSSO/);assert.equal(get('restart-connect').hidden,false);assert.equal(get('confirm-connect').disabled,true);});
test('callback error is displayed and query removed from browser history',async()=>{const {get,historyCleared}=await setup('?error=XBOX_TOKEN_UPSTREAM_HTTP_400');assert.equal(historyCleared,true);assert.match(get('message').textContent,/Microsoft/);});
test('Nintendo helper result opens confirmation and clears URL fragment without storing tokens',async()=>{const url='npf5c38e31cd085304b://auth#state='+('a'.repeat(43))+'&session_token_code=fixture';const {get,historyCleared}=await setup('','#nintendo-result='+encodeURIComponent(url));assert.equal(historyCleared,true);assert.equal(get('connect-dialog').open,true);assert.equal(get('connect-input').value,url);assert.equal(get('official-login').hidden,true);assert.doesNotMatch(source,/localStorage|sessionStorage/);});

test('Nintendo manual flow rejects wrong URL without consuming state then accepts complete matching callback',async()=>{
 const {get,calls}=await setup();const card=get('accounts').children.find(c=>c.children[0].textContent==='nintendo');await card.children.at(-1).children[0].onclick();assert.match(get('connect-guide').textContent,/无需安装软件/);assert.equal(get('nintendo-help').hidden,false);
 for(const url of ['https://accounts.nintendo.com/','npf5c38e31cd085304b://auth#state=wrong&session_token_code=fixture','npf5c38e31cd085304b://auth#state='+('a'.repeat(43))]){get('connect-input').value=url;await get('connect-form').onsubmit({preventDefault(){}});assert.match(get('connect-message').textContent,/本次任天堂/);assert.equal(get('confirm-connect').disabled,false);assert.equal(get('connect-dialog').open,true);}
 assert.equal(calls.filter(c=>c.url.endsWith('/complete/nintendo')).length,0);
 const callback='npf5c38e31cd085304b://auth#state='+('a'.repeat(43))+'&session_token_code=fixture';get('connect-input').value=' '+callback+' ';await get('connect-form').onsubmit({preventDefault(){}});const complete=calls.filter(c=>c.url.endsWith('/complete/nintendo'));assert.equal(complete.length,1);assert.deepEqual(JSON.parse(complete[0].body),{state:'a'.repeat(43),input:callback});assert.equal(get('connect-dialog').open,false);assert.equal(get('connect-input').value,'');assert.doesNotMatch(source,/localStorage|sessionStorage|clipboard\.read/);
});
test('Nintendo instructions use manual callback without installer or cloud login',()=>{const html=fs.readFileSync('public/sveltia/accounts.html','utf8');assert.doesNotMatch(html,/nintendo-callback\.ps1|PowerShell|返回助手/);assert.match(html,/复制链接地址/);assert.match(html,/换电脑无需重新绑定/);assert.match(html,/20261011-nintendo-manual/);});
